simulation_settings:
  - Name: realistic
    N: 10
    R0: 1.45 #fm
    R_last: 200 #fm
    m: 3727.3793 #MeV
    V0: -134 #MeV
    E_bind_alpha: 2.4249 # binding energy of alpha particle
    pot_method: realistic


data:
  - Symbol: Po-212
    A_parent: 212 # polonium
    Z_parent: 84 # polonium
    E_bind_p: -10.3694 # MeV
    E_bind_d: -21.7480 # MeV
    half_life: 299e-9 # s
  - Symbol: U-238
    A_parent: 238
    Z_parent: 92
    E_bind_p: 47.3089 # MeV
    E_bind_d: 40.6140 # MeV
    half_life: 1.4033e18 # s
  - Symbol: Rn-222
    A_parent: 222
    Z_parent: 86
    E_bind_p: 16.366 # MeV
    E_bind_d: 8.3516 # MeV
    half_life: 330350.4 # s